version: '3.9'
services:
  mysql_db:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-pass
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: projetopi_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    ports:
     - "8989:80"
    environment:
     PMA_HOST: mysql_db
     PMA_PORT: 3306
    depends_on:
     - mysql_db
     
  # projetopi-backend:
  #   container_name: projetopi_backend
  #   build: .
  #   environment:
  #     DATABASE_URL: jdbc:mysql://mysql_db:3306/projetopi_db
  #     DATABASE_URL_USERNAME: root
  #     DATABASE_URL_PASSWORD: secret-pass
  #   ports:
  #     - 8000:8000
  #   command: mvn spring-boot:run
  #   depends_on:
  #     - mysql_dbdo